<div id="column-center">
	<p>
		<span style="font-size:12px;"><span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">We do not disclose, rent or lease any information submitted to us to 3rd parties for marketing purposes, except as stated in this policy.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">We do not use any of your data for any reason, except as stated in this policy, but to successfully ship your order to you. You have the option to sign up for an account in the checkout process. This means that your user data is stored on our servers.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">We store your name, address and telephone number if you register for an account with us.&nbsp; This is optional, but enables you to place further orders without having to enter your details again. Your details are also stored in relation to unregistered orders.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">We use cookies to allow us to store tracking information to make your user experience better. Cookie storage includes: Items in your shopping basket, usage statistics, and your favourite products. This information is not shared, and is deleted after a reasonable period of time.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">We collect and store data in cookies which is sent securely to remarketing companies, whose algorithms may determine if you will see advertising related to your browsing on other websites. You are able to opt out of these adverts at any time.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">We do not store your credit card information. It is processed over a secure SSL/256 bit encryption system which goes through the payment provider Sagepay. We do not even see it, therefore it cannot be &#39;hacked&#39; from our servers.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">Optionally, you can supply us with a telephone number when ordering.&nbsp; This is generally only used if we are unable to contact you via email.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">If you wish, you can contact us to have your profile deleted at any point in time. All sensitive information is processed over a secure servers.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">We do not send marketing emails to random personal email address (spam), however from time to time we may send newsletters and special offers to registered customer email addresses. All of which include a facility for you to unsubscribe from such service by clicking on the link at the bottom of every newsletter sent. You can unsubscribe from our newsletter using this process anytime. To subscribe for the newsletter, you must opt in. Either in the checkout, or elsewhere on the site.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">During the checkout process, we may temporarily store your email address. This is not used for marketing purposes unless you opt into the newsletter. We may send you follow up email(s) if you do not complete the checkout process to remind you of the items in your cart for future reference.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; line-height: 16.5px; -webkit-text-size-adjust: none; ">All of our data collection and storage conforms to the requirements of the Data Protection.</span></span></p>
</div>
<p>
	&nbsp;</p>
