<div id="column-center">
	<p>
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">1. Initial introduction</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;By making a purchase with us, you are agreeing to the following terms and conditions. It is your own responsibility to ensure that you are fully aware of all of these terms and conditions when making a purchase with our online shop. These terms and conditions can be alterered at any time, so you should read them every time you make a purchase on this website.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">2. Payment</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">Payment is taken from your card at approximately 2 am in the morning on the day following the time it is despatched, when all of our processing is performed. If you wish to cancel an order after this, simply let us know and we will refund the amount in full. Payment is only taken when your goods are ready for despatch. However, when using credit card to pay, your payment may be instant and therefore unable to be delayed until the time of despatch. If an item is cancelled before it is despatched and it has been charged, it will be refunded.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">3. The contract of sale</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">On occasion, an item may be mispriced. If you purchase a mis-priced item, we reserve the right to cancel the contract and relist the product at the correct price. We reserve the right to cancel any order at any time prior to delivery, for any reason - No contract of sales exists until your order is verified by a human, and the order status is set to &#39;Verified&#39;.&nbsp; Our initial order status, &lsquo;Processed&rsquo; does not mean that a contract of sale is in place.&nbsp; This only means that the order has been successfully received into our system.&nbsp; From there on, validity and verification must take place before the contract of sale exists. The contract made between us through any transaction is governed by the laws.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">4. Security</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;Your IP is logged when placing an order. This is for reasons of fraud protection. All orders are scanned strictly for fraud by our fraud department before they are shipped. If you specify a different shipping address to the billing address then your order may take longer as we have to perform the necessary checks. Fraudulent orders will be submitted to the appropriate authorities.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">5. Prices</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">Our prices change always. Generally, we release new prices on a schedule and prices change at midnight only, and we also inform you of this scheduled price change in advance on the product page. However, we may also update prices during working hours. We do not have control over prices listed on external sites, including Google cached listings, shopping feeds or any other site. We are not obliged to provide products for any price which is listed on an external site. We do not have control of the rate at which search engines crawl our site, and therefore the information in the search results may not be indicative of up to date prices.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">6. Returns and the cooling off period</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">Please ensure you have read our refund and returns policy and understand it fully. This does not affect your statutory consumer rights. Refunds are processed as promptly as possible.&nbsp; However returns volume is unpredictable, so therefore please allow up to 14 days for the refund to be complete. Items which have been worn are not eligible under this refund policy. You should refer to our up to date returns policy. If a visual defect is found with the item(s) on arrival (out of the box), you must notify us within 48 hours.</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">7. Risk and title change</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;</span><br style="border: medium none; list-style: none outside none; margin: 0px; outline-style: none; outline-width: medium; padding: 0px; -webkit-text-size-adjust: none; color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; " />
		<span style="color: rgb(51, 51, 51); font-family: Verdana, Helvetica, sans-serif; font-size: 11px; line-height: 16.5px; -webkit-text-size-adjust: none; ">&nbsp;Risk of loss and damage of products is assumed by you from the moment the product(s) are delivered.</span></p>
</div>
<p>
	&nbsp;</p>
